apiVersion: v1
kind: ConfigMap
metadata:
  name: reviewsentinel-config
  namespace: reviewsentinel
data:
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  OLLAMA_BASE_URL: "http://ollama:11434"
  SEARCH_INDEX_DIR: "/app/artifacts/search/"
  SENTENCE_TRANSFORMER_MODEL: "all-MiniLM-L6-v2"
  MODEL_DIR: "/app/artifacts/models/distilbert-finetuned/"
  LOG_LEVEL: "INFO"
  PYTHONPATH: "/app"
