apiVersion: v1
kind: Service
metadata:
  name: reviewsentinel-api
  namespace: reviewsentinel
  labels:
    app: reviewsentinel-api
    project: reviewsentinel
spec:
  selector:
    app: reviewsentinel-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP    # internal only — external access via Ingress
