apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reviewsentinel

resources:
  - ../../base

patches:
  - path: patches/api-resources.yaml
    target:
      kind: Deployment
      name: reviewsentinel-api
  
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: reviewsentinel-api

images:
  - name: reviewsentinel/api
    newTag: "1.0.0"    # override latest with specific tag in production
