apiVersion: v1
kind: Secret
metadata:
  name: reviewsentinel-secrets
type: Opaque
stringData: # stringData allows plain text (Kubernetes will encode it automatically)
  MINIO_ROOT_USER: "reviewsentinel"          # Update with your .env value
  MINIO_ROOT_PASSWORD: "changeme123"   # Update with your .env value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reviewsentinel-configs
data:
  MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
  PREFECT_API_URL: "http://prefect-server:4200/api"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
---
# PVCs for internal app state
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prefect-data-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi