apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: reviewsentinel
  labels:
    app: ollama
    project: reviewsentinel
spec:
  selector:
    app: ollama
  ports:
    - name: ollama-api
      port: 11434
      targetPort: 11434
      protocol: TCP
  type: ClusterIP
