version: '3.8'

services:
  api:
    command: ["--reload"]
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - ../src:/app/src

  prefect-worker:
    environment:
      LOG_LEVEL: DEBUG

  mlflow:
    environment:
      LOG_LEVEL: DEBUG
      
  prefect-init:
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - ../scripts:/app/scripts  # live-reload your script too
