apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: reviewsentinel
  labels:
    app: prefect-server
    project: reviewsentinel
spec:
  selector:
    app: prefect-server
  ports:
    - name: prefect-ui
      port: 4200
      targetPort: 4200
      protocol: TCP
  type: ClusterIP
