apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reviewsentinel

resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/configmap.yaml
  - api/hpa.yaml
  - mlflow/statefulset.yaml
  - mlflow/service.yaml
  - mlflow/pvc.yaml
  - prefect/server-statefulset.yaml
  - prefect/worker-deployment.yaml
  - prefect/server-service.yaml
  - prefect/pvc.yaml
  - ollama/statefulset.yaml
  - ollama/service.yaml
  - ollama/pvc.yaml
  - minio/statefulset.yaml
  - minio/service.yaml
  - minio/pvc.yaml
  - ingress/ingress.yaml

commonLabels:
  project: reviewsentinel
  managed-by: kustomize
