apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/docker-compose.prod.yaml -o k8s/base/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prefect-worker
  name: prefect-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prefect-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/docker-compose.prod.yaml -o k8s/base/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/reviewsentinel-net: "true"
        io.kompose.service: prefect-worker
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: reviewsentinel
            - name: AWS_SECRET_ACCESS_KEY
              value: changeme123
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: PREFECT_API_URL
            - name: API_URL
              value: "http://api:8000"
            - name: API_HOST
              value: "http://api:8000"
            - name: REVIEW_API_URL
              value: "http://api:8000"
              value: http://prefect-server:4200/api
          image: ghcr.io/buzel-112/reviewsentinel-prefect-worker:latest
          args: ["worker"]
          name: reviewsentinel-prefect-worker
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: prefect-worker-claim0
            - mountPath: /app/artifacts
              name: prefect-worker-claim1
            - mountPath: /app/configs
              name: prefect-worker-claim2
      restartPolicy: Always
      volumes:
        - name: prefect-worker-claim0
          persistentVolumeClaim:
            claimName: prefect-worker-claim0
        - name: prefect-worker-claim1
          persistentVolumeClaim:
            claimName: prefect-worker-claim1
        - name: prefect-worker-claim2
          persistentVolumeClaim:
            claimName: prefect-worker-claim2
status: {}
